CREATE TABLE Cars (
	Id INT PRIMARY KEY IDENTITY(1,1),
	CarName NVARCHAR(300) NOT NULL,
	Odometer FLOAT NOT NULL,
	Engine NVARCHAR(200) NOT NULL,
	[Description] NVARCHAR(MAX),
	Colour NVARCHAR(100),
)

CREATE TABLE Advertisements (
	Id INT PRIMARY KEY IDENTITY(1,1),
	CarId INT, 
	Price INT NOT NULL,

	FOREIGN KEY (CarId) REFERENCES Cars(Id),
)
